name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.7"
          cache: true

      - name: Dependências
        run: flutter pub get

      - name: Verificação
        run: flutter analyze

      - name: Gerar APK
        run: flutter build apk --release

      - name: Publicar APK
        uses: actions/upload-artifact@v4
        with:
          name: AI-Creator-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
